#+TITLE: Coming Out as a Human Being with Deviances
#+OPTIONS: toc:nil 
#+OPTIONS: num:nil
#+OPTIONS: date:nil 
#+OPTIONS: author:nil 

* Invisible Deviances

We humans are a diverse species.  Each of us is unique, even
"so-called identical" twins.  We all differ from the norm (average) in
various ways and amounts.  Some of our deviances are visible: the
appearance of our bodies, our speech (including languages and
accents), clothes, overt cultural practices, etc.  Other deviances are
invisible, including subtle to profound differences in biological sex,
psychological gender, and ways that our brains operate.  Diversity in
brain function is called "neural diversity".  I'm deviant in the way
my brain works, in my gender identity and some subtle sexual
characteristics.  I've come to appreciate these deviances, to see them
as advantages.  And they've also been significant challenges
throughout my life.

I'm clear that despite our deviances, we humans are more alike than we
are different.  We all have the same basic consciousness, the same
fundamental needs and feelings, etc.  Fundamentally, you and I are
fellow humans and it would be ideal if we could appreciate all of the
interesting and potentially valuable differences and viewpoints which
each of us bring to the table.  Unfortunately, we humans have a long
history of intolerance towards deviance.  Most of us have received
some of that intolerance, othering and exclusion. Some of us have
received a lot of it.  I'm not very special in this regard.

When I was growing up, many of my fellow children treated me poorly.
A few adults I encountered, mostly school officials, were abusive.
Starting from an early age I realized I was deviant, that how I was
was not acceptable to many others and that I needed to mask my
deviance - a difficult task since I neither understood my deviance nor
the norm which I was deviating from!  I feared that I was somehow
badly broken, a horrible feeling!  Trying to connect with others was
often frustrating, confusing and alienating.  I'm not an extrovert and
I've always been comfortable being by myself much of the time, but
not all the time.  My social needs have rarely been well met and I've
usually been lonely.  Trying to meet my social needs while masking
(trying to be what I'm not) has never gone very well.  Trying to
communicate this to my few friends was always difficult since I didn't
understand it myself for the longest time.

* I'm on the Autistic Spectrum

First and very important: At a fundamental level my deviances don't
matter.  To my friends they're not a big deal or are even attractive.
I hope you have the same acceptance with your deviances!  People with
modern attitudes are increasingly tolerant of deviances, often to the
extent of appreciating them.  Alas, invisible deviances can sometimes
be less tolerated or appreciated because they are not seen clearly,
are not understood or are misunderstood.  For example, people who
don't show their emotions on their faces are assumed (very
incorrectly) to not have any feelings.

I'm on the lucky (high-functioning) end of the Autistic Spectrum.
What used to be called Asperger's Syndrome.  My father had the same
thing: In his spare time he played and composed beautiful music. In
his day job he was a rocket engineer.  He was intellectually brilliant
and he never understood people very well, including himself.  I'm kind
of like him but I'm also like my mother who is empathic.  I've always
been pretty good at reading other people's emotions and intentions
when I was in the role of an observer but not when I was interacting
with someone and not my own emotions and intentions. I also struggled
with understanding social conventions and things like appropriate eye
gaze.  I was never "diagnosed" with Asperger's Syndrome.  I think that
was a blessing, as people without a clue would have tried to "help"
me.  Instead, I was assessed as "intellectually gifted", which is true
as far as it goes.  I was intellectually gifted enough to realize at
an early age that I was socially disabled!

* I'm Non-Binary

Another big deviance is that I'm non-binary.  What does this mean?
Well, let's start with the binary gender experienced by most people.
It seems that most people acquire their culture's gender models at a
young age, as they acquire their native language and all of the other
basic elements of their culture.  Most people see whether they are a
boy or a girl, and later whether they're a man or a woman as an
essential part of who they are.  Most people relate to others through
that binary lens, almost always specifying someone's gender as
essential information when describing something about them: People
commonly say "I met a man who ..." or "I met a woman who ..." but not
"I met a person who ...".  Our traditional third person pronouns
require that we specify someone's gender.  For most people, gender
occurs as an essential characteristic of themselves and of others.

If you don't think that these categories are all that important, have
you heard about the situation of people who have gender dysphoria?
People whose sex doesn't match their gender identity?  Gender
dysphoria can be extremely traumatic.  Like most biological and
psychological phenomena, categories are only approximations to
reality.  If you'd like to understand this better I highly recommend
the video [[https://youtu.be/nVQplt7Chos?si=gJUOv4ctwSRseyA0][Sex and Sensibility]] by Forrest Valkai.  Going forward I'll
assume that you have some understanding of these issues.

Gender Identity is a second "spectrum" and within that spectrum
Non-Binary might be the simplest Gender Identity: None!  I don't
identify with being a man or a woman.  I never identified as a boy or
as a girl.  I have a fairly typical male body, although not strongly
masculine.  Some of my psychological characteristics are more typical
in men, others more typical in women.  This is common in both Binary
and Non-Binary people, but typically more so with Non-Binary people
when we're not masking.  I get to use, enjoy and care for my male body
like everyone does who has a male body.  I just don't think that
having a male body has anything to say about who I am or how I should
behave or feel in contrast to people who have female bodies or
intersex bodies.  I've learned to pay attention to whether people I'm
interacting with want me to acknowledge their gender, as I don't have
any automatic tendency to do so.

* I'm Demi-Sexual

It's possible that my being non-binary is one of the expressions of my
being on the autistic spectrum, not that that matters!  I imagine that
when I was at the critical age to acquire gender information from my
culture, my brain was doing something else.  Maybe my brain was busy
learning about physics instead - I don't know!  In addition to being
non-binary I'm demi-sexual  I don't have as strong a sex drive as
most people I know.  This is another spectrum.  Some people have
sexual feelings and thoughts frequently, some occasionally and a few
not at all.  I'm in that middle group.  I love hugging and cuddling
and it's not sexual for me.  I would like to have more intimate
physical non-sexual contact than I get.  I like people.  I easily
develop strong non-sexual love for people. I imagine and hope that you
also have love in your metaphorical heart for many people who you
don't happen to have a sexual interest in.

I've had a few loving sexual relationships.  I've never experienced
romantic or sexual jealousy but compersion comes naturally to me.
Being non-binary and not experiencing jealousy I have sometimes
identified as bisexual and polyamorous.  These labels aren't wrong,
but most of the bisexual and polyamorous people I know seem to have a
higher sex drive than I do, so these characteristics may be somewhat a
function of my being demi-sexual.  I sometimes feel that I'm missing
out on some wonderful experiences that my more sexual friends have and
I also feel a great deal of relief from what they seem to have to deal
with!

* Aphantasia and Alternative Mental Structures

Almost everyone has the ability to bring up images in their minds: the
face of people they know, familiar scenes, etc.  How well people can
do this varies enormously.  About 2½% of people can't do it at
all.  Those people are called /aphantasic/.

I'm Aphantasic.

** What's It Like To Be Aphantasic?

When I close my eyes I see darkness.
- I can't summon up an image of
  - my mother's face
  - my house
  - anything!
- I can't see what anything looks like unless I'm looking at that
  thing with my actual eyes.

** What are the consequences of aphantasia?

Aphantasia has remarkably little consequence

- Aphantasia has no impact on IQ.
- Aphantasia doesn't keep people from being creative with the visual
  arts.
- Many prominent intelligent and creative people are Aphantasic.
  
** What I Do And Don't Think With

When I'm thinking there are
- No images
- No words or expressions of human language

I think very abstractly
- It seems like I have direct experience of abstract concepts
  - What does this really mean?
  - I don't know, I only know what it seems like!

When I speak I have to translate from my internal abstract non-visual
and non-verbal world into human language.  I'm very good at this and
on occasion I have trouble putting into language things that seem
simple and clear and present to me as concepts.

What I'd like you to get from this part of this "coming out" document
is that
- Different people have /very different/ internal worlds
- Mine is /probably/ very different from yours
- If yours is like mine, it's very different from most people's!

If you want to know more about what my internal world is like, please see
- [[file:mental-imagery-and-me.org][Mental Imagery and My Internal World]]

* My Prosopagnosia and Dysnomia

Translation:
- I have trouble recognizing faces.
- I have trouble remembering people's names.

If I don't recognize you or I don't remember your name
- It's not because I don't care about you!
- I probably care about you very much!

I might need a reminder of who you are when we encounter one another
- It may take me a few moments to remember who you are,
- then I'll be present to how much I appreciate you!

If you're someone who is good with faces or names
- Get that you're privileged!
- Notice any assumptions you have about those who lack that privilege!
- See if you can include us without judgement! 

* So What?

What does all of this mean and why am I bothering to reveal these
characteristics?
- I don't think that these ways in which I deviate from the norm have
  to be a big deal.
- Yet they can get in the way
  - If they activate other people's prejudices
  - including the fear of differences they don't understand.
  - Trying to hide and/or mask these differences has a cost!

In one way I'm privileged that my deviances are mostly invisible.  If
I avoid mentioning them and mask the "tells", most people unfamiliar
with my kind of deviance won't guess, although they may feel that
there's something inauthentic about me.  I hide and mask my
differences with most people to avoid being othered by people who
won't understand or won't appreciate my deviances.  So that I won't be
excluded or attacked (both of which happened a lot when I was a child)
and so I won't have to deal with being misunderstood: I would rather
that people not understand me than believe false things about me.

I developed my strategies for hiding and masking when I was young and
insecure.  Since then I've grown up - as has modern culture, at least
in the more educated and aware circles I inhabit.  I have the many
privileges of being an adult whose speech indicates that I'm of the
well-educated elite.  I have exciting and potentially revolutionary
projects which I'd like to share with people.  I have a personal need
for connection with others - especially since my primary partner died
some years ago.  Hiding and masking is costing me far more than
exposure.

I've decided to take off the mask with more people.  To not worry so
much about these things.  To deal with peoples' reactions as I've
always had to anyway.  And hopefully as a result, to connect with more
people who share my interests and values and either don't care about
my deviances or kinda like them!

Thanks for learning a bit more about me!

#+begin_quote
Security is mostly a superstition. It does not exist in nature, nor do
the children of men as a whole experience it. Avoiding danger is no
safer in the long run than outright exposure. Life is either a daring
adventure, or nothing.

― Helen Keller, /The Open Door/
#+end_quote

#+begin_quote
And the day came when the risk to remain tight in a bud was more
painful than the risk it took to blossom.

― Anaïs Nin
#+end_quote
