* Coming Out as a Human Being with Deviances

** Invisible Deviances

We humans are a diverse species.  Each of us is unique, even
"so-called identical" twins.  We all differ from the norm (average) in
various ways and amounts.  Some of our deviances are visible: the
appearance of our bodies, our speech (including languages and
accents), clothes, overt cultural practices, etc.  Other deviances
are invisible, including: subtle to profound differences in biological
sex, psychological gender, and ways that our brains operate.
Diversity in brain function is called "neural diversity".  I'm deviant
in the way my brain works, in my gender identity and possibly in some
subtle sexual characteristics.  I've come to appreciate these
deviances, to see them as advantages.  And they've also been
significant challenges throughout my life.

I'm clear that despite our deviances, we humans are more alike than we
are different.  We all have the same basic consciousness, the same
fundamental needs and feelings, etc.  Fundamentally, you and I are
fellow humans.  It is still useful to appreciate the different forms
our humanness takes, lest we cause harm by othering and excluding
people because of unfamiliar benign, and potentially interesting and
valuable, differences.  Unfortunately, we humans have a long history
of intolerance towards deviance.  Most of us have received some of
that intolerance, some of us have received a lot of it.  I'm not very
special in this regard.

When I was growing up, my fellow children often treated me badly.
Some of the adults I encountered, especially school officials, enacted
their forms of abuse.  Starting from an early age I realized I was
deviant, that how I was was not acceptable to many others and that I
needed to hide and mask my deviance - a difficult task since I neither
understood my deviance nor the norm which I was deviating from!  I
feared that my deviance was brokenness, a horrible feeling.  Trying to
connect with others was often frustrating, confusing and alienating.
I'm not an extrovert and I've always been comfortable being by myself
much of the time - but not all the time.  My social needs have rarely
been well met and I've usually been lonely.  Trying to meet my social
needs while masking (trying to be what I'm not) has never gone very
well.  Trying to communicate this to my few friends was always
difficult since I didn't understand it myself for the longest time.

** I"m on the Autistic Spectrum

First and very important: At a fundamental level my deviances don't
matter.  To my friends they're not a big deal or are even attractive.
I hope you have the same acceptance with your deviances!  People with
modern attitudes are increasingly tolerant of deviances to the extent
of appreciating them.  Alas, invisible deviances are often less
tolerated or appreciated because they are not seen clearly, are not
understood or are misunderstood.  For example, people who don't show
their emotions on their faces are assumed (very incorrectly) to not
have any feelings.

I'm on the lucky (high-functioning) end of the Autistic Spectrum.  I
have what used to be called Asperger's Syndrome.  My father had the
same thing: In his spare time he played and composed beautiful
music. In his day job he was a rocket engineer.  He was intellectually
brilliant and he never understood people very well, including himself.
I'm kind of like him but I'm also like my mother who is empathic.
I've always been pretty good at reading emotions and intentions but I
struggled with understanding social conventions.  I also wasn't aware
of how little I understood my own emotions when they were at odds with
my intentions.  I was never "diagnosed" with Asperger's Syndrome.  I
think that was a blessing, as people without a clue would have tried
to "help" me.  Instead, I was assessed as "intellectually gifted",
which is true as far as it goes.  I was intellectually gifted enough
to realize at an early age that I was socially disabled!

** I'm Non-Binary

My other big deviance is that I'm non-binary.  What does this mean?
Well, let's start with the binary gender experienced by most people.
It seems that most people acquire their culture's gender models at a
young age, as they acquire their native language and all of the other
norms of their culture.  Most people see whether they are a boy or a
girl, and later whether they're a man or a woman as an essential part
of who they are.  Most people relate to others through that binary
lens, almost always specifying someone's gender as essential
information when describing something about them: When we say "I met a
man who" vs. "I met a woman who".  Our third person pronouns require that we specify someone's gender.  For most people, gender occurs as an essential characteristic of themselves and of others.

If you don't think that these categories are all that important, have
you heard about the situation of people who have gender dysphoria?
People who's sex doesn't match their gender identity?  Gender
dysphoria can be extremely traumatic.  Like most biological and
psychological phenomenon, categories are only approximations to
reality.  If you'd like to understand this better I highly recommend
the video [[https://youtu.be/nVQplt7Chos?si=gJUOv4ctwSRseyA0][Sex and Sensibility]] by Forrest Valkai.  Going forward I'll
assume that you have some understanding of these issues.

Non-binary might be the simplest gender identity: None!  I don't
identify with being a man or a woman.  I have a fairly typical male
body, although not strongly masculine.  Some of my psychological
characteristics are more typical in men, others more typical in
women..  This is quite common: binary people mostly ignore such
crossovers if they're not too large.  I get to use, enjoy and care for
my male body like everyone does who has a male body.  I just don't
think that having a male body means that I should behave or feel
differently than people who have female bodies or intersex bodies do.
I've learned to pay attention to whether people I'm interacting with
want me to acknowledge their gender, as I don't have any automatic
tendency to do so.

** A Few Other Pieces

I imagine that when I was at the critical age to acquire gender
information from my culture, my brain was doing something else.  Maybe
my brain was busy learning about physics instead - I don't know!  I'm
also demi-sexual.  I don't have as strong a sex drive as most people I
know.  This is another spectrum.  Some people have sexual feelings and
thoughts frequently, some occasionally and a few not at all.  I'm in
that middle group.  I love hugging and cuddling.  I would like to have
more intimate physical non-sexual contact than I get.  I tend to like
people.  I easily develop strong non-sexual love for people. I imagine
and hope that you also have love in your metaphorical heart for many
people who you don't happen to have a sexual interest in.

I've had a few wonderful romantic and sexual relationships.  I've
never experienced romantic or sexual jealousy but compersion comes
naturally.  Being non-binary and not experiencing jealousy I have
sometimes identified as bisexual and polyamorous.  These labels aren't
wrong, but most of the bisexual and polyamorous people I know seem to
have a much higher sex drive than I do, so I think these labels only
apply to me by default.

** So What?

What does all of this mean and why am I bothering to reveal these
characteristics?  Well first: I don't think that these ways in which I
deviate from the norm should be a big deal.  But: They can get in the
way if they activate other people's prejudices or fear of differences
they don't understand.  Trying to hide and/or mask these differences
has a cost.

In one way I'm privileged that my deviances are mostly invisible.  If
I avoid mentioning them and mask the "tells", most people unfamiliar
with my kind of deviance won't guess, although they may feel that
there's something inauthentic about me.  I hide and mask my
differences with most people to avoid being othered by people who
won't understand or won't appreciate my deviances.  So that I won't be
excluded or attacked (both of which happened a lot when I was a child)
and so I won't have to deal with being misunderstood: I would rather
that people not understand me than believe false things about me.

I developed my strategies for hiding and masking when I was young and
insecure.  Since then I've grown up - as has modern culture, at least
in the more educated and aware circles I inhabit.  I have the
privileges of being an adult - an older, white, male, educated adult,
in fact!  I have exciting and potentially revolutionary projects which
I'd like to share with people.  I have a personal need for connection
with others - especially since my wife died some years ago.  Hiding
and masking is costing me far more than exposure.

I'm decided to take off the mask with more people.  To not worry so
much about these things.  To deal with people's reactions as I've
always had to anyway.  And hopefully as a result, to connect with more
people who share my interests and values and either don't care about
my deviances or kinda like them!

#+begin_quote
Security is mostly a superstition. It does not exist in nature, nor do
the children of men as a whole experience it. Avoiding danger is no
safer in the long run than outright exposure. Life is either a daring
adventure, or nothing.

― Helen Keller, The Open Door 
#+end_quote

#+begin_quote
And the day came when the risk to remain tight in a bud was more
painful than the risk it took to blossom.

― Anaïs Nin
#+end_quote
