* Please Share Abundance With Me!

What I'd like for holiday gifts and for the Happy New Years to come is
[[file:abundance.org][Abundance]].  I want it for me and I want it for us.

I am asking for a growing consilient and diverse worldwide movement
for abundance.  I see this movement as having three great parts:
Individual, Relational and Material.

At the Individual level, I would like all of us to have [[https://touchpuuhonua.github.io/SomeClues][Some Clues]] and
to get our [[https://www.cnvc.org/training/resource/needs-inventory][common human needs]] met.  I would like all barriers to our
creativity, growth, development and productivity taken down.

At the level of our relationships with one another, within our groups,
organizations, communities, networks and other associations I would
like all of our interactions being win-win.  Good for me, good for you
and good for everyone else impacted by what we do.  I would like all
of our interactions to occur within a context of empathy and
unconditional respect.

At the material level, I would like urgent strategic action to
abundantly meet the material needs of all human beings, starting with
the needs of everyone in our smaller associations and rapidly growing
to the needs of everyone in our largest associations.  I would like us
working together to elminate all barriers to creative productivity,
especially learning and knowledge.

One side of all of this is non-material, yet we cannot have it all
without the other side, Material Abundance:

- Automated Flexible Production including [[https://fabfoundation.org/getting-started][Fab Labs]] which allow
  everyone who can create or leverage open source designs to
  manufacture those designs affordably for themselves and their
  communities.  All Fab Labs producing the components for easily
  creating new Fab Labs causing exponential expansion until Fab Labs
  are abundantly available for everyone everywhere.
- AI and Fab Labs amplifying the experience of medical knowledge
  workers to make high quality medical services affordable to
  everyone.
- Learner-based Education consistent with the ideas of Maria
  Montessori and Seymour Papert.  Most formal knowledge learned within
  individual and group immersive simulations using open source
  computer game engines.  I will be working on this through [[https://github.com/GregDavidson/loel#readme][the League
  of Extraordinary Learners]]
- Targeted work on nanoscale replicator technologies: molecular
  biology and [[https://www.youtube.com/watch?v=Q9RiB_o7Szs][molecular nanotechnology]], the ultimate technologies for
  ending all material scarcity including slowing and eventually
  stopping and reversing aging.  There are many paths to programable
  molecular assemblers, just waiting for us to make their development
  a priority.

This is a big gift I want, maybe the biggest!  It will require a great
diversity of people to fulfill it.  It will require many people to
step up to fulfilling their dreams.  Operating from abundance
leverages the resources of understanding, knowledge and replication
technolgies to generate more resources in an exponential runaway. This
is what's been accelerating in the world for generations.  Let's make
it run even faster: We can have this gift if we give to one another.
